### ISSUE TITLE
Hey faheem it's mojammel

### ISSUE THREAD

**Issue by ghost** [qwerty12/NFCLockscreenoffEnabler#4]
It's been a long time. Just typed your name into Google to see if I could find you on Facebook. But I found you here. Whatsapp me please [number removed]

**Comment by qwerty12** [comment]
1. No, I can't teach you how to program. For one, I don't know PHP and my small Android hacks were just that: small. I haven't touched the Android SDK in a very long time; the little I did know about Android development has long since been forgotten. 

2. It's not a good idea to post your phone number publicly. I've taken the liberty of editing it out for you

3. You know exactly why I can't trust you. I would've understood had you said my name back then out of coercion, but, no, you did it to "buy yourselves some more time". I'll never forgive you for that.

**Comment by MojammelW** [comment]
1 it's OK I was just planning to talk to you about programming not for you
to teach me.
I'm using team treehouse.
2 thanks for that
3 I apologise wholeheartedly for giving your name that day. It wasn't to
buy more time even if that's what was said. What happened was I was coerced
by siddique to tell your name cos he said something like blame fahim I
stupidly did it following siddiques orders without thinking it through we
were put on the Spot and I was pressured into blaming you.
 I didnt have anything against you.
And they kind of did want to know where we got the far manager. Then after
you were blamed by me as was suggested to me first by siddique he then
didn't blame you and let you and me take the exclusion and he got excluded
anyway. Basically siddique tricked me. By pressuring me to blame you on the
spot.

I don't know what he gained from getting me to blame you other than
separating us from being friends.

I hope you can forgive me for this mistake, even if you forgive me I'll
understand if you still hold a resentment towards me. We were kids and I'm
not an untrustworthy man now. Sorry for what happened in the past. Me and
siddique had a serious falling out when we were about 18 just to let you
know we're not friends anymore. He's very snakey and dangerous.

Ps. None of it was my plan it was all him and I flaked under pressure and
obeyed his orders. Till we all got in trouble for it. I even told siddique
not to hack or use the far manager but he said don't worry nothings going
to happen and he took it and used it any way. I never even planned to use
the far manager that day with siddique he took it he used it I got blamed
cos it was on my USB.

I hope we can move on from this, if you don't mind being friends again.
